[package]
name = "dwarfer"
version = "0.1.0"
authors = ["forestaa <t.daichi.3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
