[tasks.run]
command = "cargo"
args = ["run", "${@}"]
dependencies = ["elf-build"]

[tasks.ignored-test-body]
command = "cargo"
args = ["test", "--", "--ignored"]
dependencies = ["elf-build"]

[tasks.ignored-test]
dependencies = ["ignored-test-body"]
run_task = "elf-clean"

[tasks.elf-build]
command = "make"
args = ["-C", "examples", "all"]

[tasks.elf-clean]
command = "make"
args = ["-C", "examples", "clean"]

[tasks.test-flow]
dependencies = ["test"]

[tasks.all-test-flow]
dependencies = ["test", "ignored-test"]
